<a href="https://colab.research.google.com/github/brownethan/cs315/blob/main/HW09Prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
input_string = "hheieotrk"

matrix = np.array([])

for char in input_string:
    matrix = np.append(matrix, char)

rows_cols = int(len(input_string)**0.5) # Calculate rows_cols based on string length
matrix = matrix.reshape(rows_cols, rows_cols)

print("1. Caesar Square Decryption Setup (Matrix):")
print(matrix)


1. Caesar Square Decryption Setup (Matrix):
[['h' 'h' 'e']
 ['i' 'e' 'o']
 ['t' 'r' 'k']]


In [7]:
input_string = "104 105 97 108 108"

ascii_numbers_list = input_string.split()
decrypted_output = ""

# Iterate through the list of ASCII number strings
for num in ascii_numbers_list:
    # Convert the string number to an integer ASCII code using int(num)
    char_code = int(num)

    # Apply Decryption Shift (e.g., char_code - 3)
    decrypted_code = char_code

    # Convert the ASCII code back to a character using chr(char_code)
    decrypted_char = chr(decrypted_code)

    decrypted_output += decrypted_char

print("\n2. Caesar Cipher Decryption:")
print(decrypted_output)


2. Caesar Cipher Decryption:
hiall


In [9]:
input_string = "hi all"

ascii_numbers_list = []

# Iterate through the input string
for char in input_string:
    # Get the ASCII code using the ord(char) hint
    char_ascii_code = ord(char)
    ascii_numbers_list.append(str(char_ascii_code))

output_string = " ".join(ascii_numbers_list)

print("\n3. String to ASCII Numbers:")
print(output_string)


3. String to ASCII Numbers:
104 105 32 97 108 108


In [10]:
import numpy as np

# --- USER INPUT (Example Matrices) ---
# A: Encryption Key (2x2)
A = np.array([[2, 3], [4, 1]])

# B_original: Hypothetical original message (used to generate C)
B_original = np.array([[104, 101, 121], [97, 108, 108]])

# C: Encrypted Message (calculated using C = np.dot(A, B_original))
C = np.dot(A, B_original)
# -----------------------------------

# 1. Calculate the inverse of the encryption key matrix (A_inv)
# Use the np.linalg.inv(A) hint
Ainv = np.linalg.inv(A)

# 2. Recover the original message (B) using matrix multiplication: B = A_inv * C
# Use the np.dot(Ainv, C) hint
B = np.dot(Ainv, C)

print("\n4. Message Recovery via Matrix Inversion:")
print("Encrypted Message (C):\n", C)
print("\nInverse of Key Matrix (Ainv):\n", Ainv)
print("\nOriginal Message Recovered (B = Ainv * C):\n", B)


4. Message Recovery via Matrix Inversion:
Encrypted Message (C):
 [[499 526 566]
 [513 512 592]]

Inverse of Key Matrix (Ainv):
 [[-0.1  0.3]
 [ 0.4 -0.2]]

Original Message Recovered (B = Ainv * C):
 [[104. 101. 121.]
 [ 97. 108. 108.]]
